// Dados fictícios e ilustrativos; a lista de conceitos é a PROPOSTA D4 validada, e este arquivo NÃO é seed — o seed pertence à Etapa 4.
import type { GraphViewEnvelope } from '@/application/read-models/graph-view-contract';

export const graphViewMock = {
  data: {
    discipline: {
      id: 'discipline-statistics',
      name: 'Estatística I',
      semester: 'semestre-ficticio',
    },
    nodes: [
      {
        id: 'module-fundamentals',
        type: 'MODULE',
        title: 'Fundamentos',
        description: 'Conceitos fundamentais para organizar e representar dados.',
      },
      {
        id: 'module-central-tendency',
        type: 'MODULE',
        title: 'Tendência central',
        description: 'Medidas que representam valores centrais de uma distribuição.',
      },
      {
        id: 'module-dispersion',
        type: 'MODULE',
        title: 'Dispersão',
        description: 'Medidas que descrevem a variabilidade dos dados.',
      },
      {
        id: 'module-exploratory-analysis',
        type: 'MODULE',
        title: 'Análise exploratória',
        description: 'Recursos para investigar distribuição, forma e associação.',
      },
      {
        id: 'concept-population-sample',
        type: 'CONCEPT',
        title: 'População e amostra',
        description: 'Distinção entre o conjunto de interesse e sua parcela observada.',
        learningState: 'LIKELY_UNDERSTOOD',
        explanation:
          'Calculado por state-rules/v1 R5: evidências de origens distintas incluem uma atividade correta.',
      },
      {
        id: 'concept-variable-types',
        type: 'CONCEPT',
        title: 'Tipos de variáveis',
        description: 'Classificação de variáveis usadas em uma análise.',
        learningState: 'IN_PROGRESS',
        explanation: 'Calculado por state-rules/v1 R6: existe evidência de estudo do conceito.',
      },
      {
        id: 'concept-frequency-tables',
        type: 'CONCEPT',
        title: 'Tabelas de frequência',
        description: 'Organização das ocorrências de valores ou classes.',
        learningState: 'IN_PROGRESS',
        explanation: 'Calculado por state-rules/v1 R6: existe evidência de acesso ao conceito.',
      },
      {
        id: 'concept-histogram',
        type: 'CONCEPT',
        title: 'Histograma',
        description: 'Representação gráfica de uma distribuição de frequências.',
        learningState: 'NOT_STARTED',
        explanation: 'Calculado por state-rules/v1 R7: não existe evidência para o conceito.',
      },
      {
        id: 'concept-arithmetic-mean',
        type: 'CONCEPT',
        title: 'Média aritmética',
        description: 'Soma dos valores dividida pela quantidade de observações.',
        learningState: 'POSSIBLE_DIFFICULTY',
        explanation:
          'Calculado por state-rules/v1 R2: existe dúvida detectada sem sessão de estudo concluída.',
      },
      {
        id: 'concept-median',
        type: 'CONCEPT',
        title: 'Mediana',
        description: 'Valor central dos dados após sua ordenação.',
        learningState: 'POSSIBLE_DIFFICULTY',
        explanation:
          'Calculado por state-rules/v1 R2: existe dúvida detectada sem sessão de estudo concluída.',
      },
      {
        id: 'concept-mode',
        type: 'CONCEPT',
        title: 'Moda',
        description: 'Valor ou classe de maior frequência.',
        learningState: 'LIKELY_UNDERSTOOD',
        explanation:
          'Calculado por state-rules/v1 R5: evidências de origens distintas incluem uma atividade correta.',
      },
      {
        id: 'concept-range',
        type: 'CONCEPT',
        title: 'Amplitude',
        description: 'Diferença entre os valores máximo e mínimo.',
        learningState: 'IN_PROGRESS',
        explanation: 'Calculado por state-rules/v1 R6: existe evidência de estudo do conceito.',
      },
      {
        id: 'concept-variance',
        type: 'CONCEPT',
        title: 'Variância',
        description: 'Medida quadrática da dispersão em torno da média.',
        learningState: 'NOT_STARTED',
        explanation: 'Calculado por state-rules/v1 R7: não existe evidência para o conceito.',
      },
      {
        id: 'concept-standard-deviation',
        type: 'CONCEPT',
        title: 'Desvio padrão',
        description: 'Raiz quadrada da variância na unidade original dos dados.',
        learningState: 'NOT_STARTED',
        explanation: 'Calculado por state-rules/v1 R7: não existe evidência para o conceito.',
      },
      {
        id: 'concept-coefficient-variation',
        type: 'CONCEPT',
        title: 'Coeficiente de variação',
        description: 'Medida relativa de dispersão.',
        learningState: 'NOT_STARTED',
        explanation: 'Calculado por state-rules/v1 R7: não existe evidência para o conceito.',
      },
      {
        id: 'concept-quartiles-percentiles',
        type: 'CONCEPT',
        title: 'Quartis e percentis',
        description: 'Pontos que dividem os dados ordenados em proporções.',
        learningState: 'IN_PROGRESS',
        explanation: 'Calculado por state-rules/v1 R6: existe evidência de estudo do conceito.',
      },
      {
        id: 'concept-boxplot',
        type: 'CONCEPT',
        title: 'Boxplot',
        description: 'Representação da distribuição por quartis e extremos.',
        learningState: 'NOT_STARTED',
        explanation: 'Calculado por state-rules/v1 R7: não existe evidência para o conceito.',
      },
      {
        id: 'concept-skewness',
        type: 'CONCEPT',
        title: 'Assimetria',
        description: 'Descrição da falta de simetria de uma distribuição.',
        learningState: 'NOT_STARTED',
        explanation: 'Calculado por state-rules/v1 R7: não existe evidência para o conceito.',
      },
      {
        id: 'concept-linear-correlation',
        type: 'CONCEPT',
        title: 'Correlação linear (noção)',
        description: 'Noção de associação linear entre duas variáveis.',
        learningState: 'NOT_STARTED',
        explanation: 'Calculado por state-rules/v1 R7: não existe evidência para o conceito.',
      },
      {
        id: 'material-central-tendency-handout',
        type: 'MATERIAL',
        title: 'Apostila de tendência central',
        materialType: 'HANDOUT',
        sourceRef: 'materials/central-tendency-handout.pdf',
      },
      {
        id: 'material-central-tendency-video',
        type: 'MATERIAL',
        title: 'Videoaula de tendência central',
        materialType: 'VIDEO',
        sourceRef: 'materials/central-tendency-video',
      },
      {
        id: 'doubt-mean-median',
        type: 'DOUBT',
        summary: 'Diferença entre média e mediana',
        createdAt: '2026-01-12T12:31:00.000Z',
      },
    ],
    edges: [
      {
        id: 'edge-population-sample-fundamentals',
        type: 'BELONGS_TO_MODULE',
        source: 'concept-population-sample',
        target: 'module-fundamentals',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-variable-types-fundamentals',
        type: 'BELONGS_TO_MODULE',
        source: 'concept-variable-types',
        target: 'module-fundamentals',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-frequency-tables-fundamentals',
        type: 'BELONGS_TO_MODULE',
        source: 'concept-frequency-tables',
        target: 'module-fundamentals',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-histogram-fundamentals',
        type: 'BELONGS_TO_MODULE',
        source: 'concept-histogram',
        target: 'module-fundamentals',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-arithmetic-mean-central-tendency',
        type: 'BELONGS_TO_MODULE',
        source: 'concept-arithmetic-mean',
        target: 'module-central-tendency',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-median-central-tendency',
        type: 'BELONGS_TO_MODULE',
        source: 'concept-median',
        target: 'module-central-tendency',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-mode-central-tendency',
        type: 'BELONGS_TO_MODULE',
        source: 'concept-mode',
        target: 'module-central-tendency',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-range-dispersion',
        type: 'BELONGS_TO_MODULE',
        source: 'concept-range',
        target: 'module-dispersion',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-variance-dispersion',
        type: 'BELONGS_TO_MODULE',
        source: 'concept-variance',
        target: 'module-dispersion',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-standard-deviation-dispersion',
        type: 'BELONGS_TO_MODULE',
        source: 'concept-standard-deviation',
        target: 'module-dispersion',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-coefficient-variation-dispersion',
        type: 'BELONGS_TO_MODULE',
        source: 'concept-coefficient-variation',
        target: 'module-dispersion',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-quartiles-percentiles-exploratory',
        type: 'BELONGS_TO_MODULE',
        source: 'concept-quartiles-percentiles',
        target: 'module-exploratory-analysis',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-boxplot-exploratory',
        type: 'BELONGS_TO_MODULE',
        source: 'concept-boxplot',
        target: 'module-exploratory-analysis',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-skewness-exploratory',
        type: 'BELONGS_TO_MODULE',
        source: 'concept-skewness',
        target: 'module-exploratory-analysis',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-linear-correlation-exploratory',
        type: 'BELONGS_TO_MODULE',
        source: 'concept-linear-correlation',
        target: 'module-exploratory-analysis',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-frequency-tables-histogram',
        type: 'PREREQUISITE_OF',
        source: 'concept-frequency-tables',
        target: 'concept-histogram',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-mean-variance',
        type: 'PREREQUISITE_OF',
        source: 'concept-arithmetic-mean',
        target: 'concept-variance',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-variance-standard-deviation',
        type: 'PREREQUISITE_OF',
        source: 'concept-variance',
        target: 'concept-standard-deviation',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-standard-deviation-coefficient-variation',
        type: 'PREREQUISITE_OF',
        source: 'concept-standard-deviation',
        target: 'concept-coefficient-variation',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-median-quartiles',
        type: 'PREREQUISITE_OF',
        source: 'concept-median',
        target: 'concept-quartiles-percentiles',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-quartiles-boxplot',
        type: 'PREREQUISITE_OF',
        source: 'concept-quartiles-percentiles',
        target: 'concept-boxplot',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-mean-skewness',
        type: 'PREREQUISITE_OF',
        source: 'concept-arithmetic-mean',
        target: 'concept-skewness',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-median-skewness',
        type: 'PREREQUISITE_OF',
        source: 'concept-median',
        target: 'concept-skewness',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-handout-mean',
        type: 'COVERS_CONCEPT',
        source: 'material-central-tendency-handout',
        target: 'concept-arithmetic-mean',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-handout-median',
        type: 'COVERS_CONCEPT',
        source: 'material-central-tendency-handout',
        target: 'concept-median',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-handout-mode',
        type: 'COVERS_CONCEPT',
        source: 'material-central-tendency-handout',
        target: 'concept-mode',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-video-mean',
        type: 'COVERS_CONCEPT',
        source: 'material-central-tendency-video',
        target: 'concept-arithmetic-mean',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-video-median',
        type: 'COVERS_CONCEPT',
        source: 'material-central-tendency-video',
        target: 'concept-median',
        evidenceKind: 'OBSERVED',
        style: 'SOLID',
      },
      {
        id: 'edge-doubt-mean',
        type: 'DOUBT_ABOUT',
        source: 'doubt-mean-median',
        target: 'concept-arithmetic-mean',
        evidenceKind: 'INFERRED',
        style: 'DASHED',
      },
      {
        id: 'edge-doubt-median',
        type: 'DOUBT_ABOUT',
        source: 'doubt-mean-median',
        target: 'concept-median',
        evidenceKind: 'INFERRED',
        style: 'DASHED',
      },
    ],
  },
  meta: {
    requestId: 'request-ficticio',
  },
} satisfies GraphViewEnvelope;
